### PR TITLE
Updating for node v0.6

### PR DESCRIPTION
**Pull request by quartzjer**
There weren't many changes in the core codebase, but this also updates all the major packages to the 0.6+ versions, so it's a pretty significant and comprehensive step forward that needs more testing.

The tests don't pass yet, but they run, so more help is needed!

### CODE REVIEW

**Comment by quartzjer** [comment]
I was able to just run this cleanly, yay!

**Comment by aflatter** [comment]
Yup, my locker runs fine too. :)

**Comment by mdz** [comment]
Not working for me:

[dashboardv3] The "sys" module is now called "util". It should have a similar interface.
[dashboardv3] 
[dashboardv3] /home/mdz/src/singly/Locker/Common/node/lconfig.js:20
[dashboardv3]             throw err;
[dashboardv3]                   ^
[dashboardv3] Error: ENOENT, no such file or directory '../../Config/config.json'

**Comment by mdz** [comment]
Sorry, wasn't up to date. temas' changes fixed this I think

**Comment by mdz** [comment]
Scratch that, it's still happening

**Comment by mdz** [comment]
Looks like it's related to my Me/ directory being a symlink. Worked fine on master/0.4 for a long time, but breaks on v6/0.6.9

**Comment by mdz** [comment]
Test suite doesn't run at all for me:

tutti:[~/src/singly/Locker/tests] node runTests.js
Locker did not start correctly, got the error: Error: Cannot find module 'lutil'

**Comment by temas** [comment]
Best testing I could get from everyone would be to do the following:
- Checkout the v6 branch
- `rm -rf node_modules`
- `npm install`
- Verify your locker runs in a way you wish
- `npm test`
- Verify all tests pass

**Comment by mdz** [comment]
Don't forget step 0. upgrade to node v0.6. :-)

On Fri, Feb 03, 2012 at 11:39:38AM -0800, Thomas Muldowney wrote:

> Best testing I could get from everyone would be to do the following:
> - Checkout the v6 branch
> - `rm -rf node_modules`
> - `npm install`
> - Verify your locker runs in a way you wish
> - `npm test`
> - Verify all tests pass
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/LockerProject/Locker/pull/533#issuecomment-3802905

## 
- mdz
